###
POST http://localhost:5000/api/v1/people/person HTTP/1.1
Content-Type: application/json

{
  "client_name": "Yaneth",
  "address":[{
    "city": "Manizales",
    "code_zip":"170002",
    "geo":[{
      "lat": -4.5985,
      "long": 0.2733
    }]
  }],
  "contact":{
    "email":"ymejia@umanizales.edu.co",
    "cellphone": "30454558**"
  }
}

###
POST http://localhost:5000/api/v1/people/person HTTP/1.1
Content-Type: application/json

{
  "client_name": "Sanyer Duque",
  "address":[{
    "city": "Manizales",
    "code_zip":"1508",
    "geo":[{
      "lat": -16.1125,
      "long": 5.0206
    }]
  }],
  "contact":{
    "email":"sduque78257@umanizales.edu.co",
    "cellphone": "3117828944"
  }
}

###
GET http://localhost:5000/api/v1/people  HTTP/1.1

###
GET http://localhost:5000/api/v1/people/623bfda43cbd78ec67c23620  HTTP/1.1

###
PUT http://localhost:5000/api/v1/people/623bfda43cbd78ec67c23620 HTTP/1.1
Content-Type: application/json

{
  "client_name": "Ezperanza Gomez",
  "address":[{
    "city": "Chinchina",
    "code_zip":"0206",
    "geo":[{
      "lat": -17.0000,
      "long": 9.2066
    }]
  }],
  "contact":{
    "email":"sanyer,duque@gmail.com",
    "cellphone": "3148434074"
  }
}

###
DELETE http://localhost:5000/api/v1/people/623cfe96b4edae515530b0a0 HTTP/1.1

